### ISSUE TITLE
Todo for Public Release

### ISSUE THREAD

**Issue by kentakang** [kentakang/auto_subtitler#1]
This project not yet ready to public release.
Below is a TODO list for the public release.

- [ ] Translation without srtranslator
- [ ] Remove firefox requirements
- [ ] Optimize speed (with whisper.cpp or other)
- [ ] Support other languages
- [ ] Support other cpu architecture
- [ ] Support arguments
- [ ] Refining documents
